 ### Get all contacts
#   GET http://localhost:3000/contacts

  ### Get single contact by ID
#   GET http://localhost:3000/contacts/69101bacd3be75a1883b337f

  ### Test invalid ID
  GET http://localhost:3000/contacts/invalidid123